SELECT P . NOMBRE PROYECTO , PR . DESCRIPCION PRODUCTO
FROM PROYECTO P
INNER JOIN PRODUCTO_PROYECTO PP 
ON P . PROYECTO = PP . PROYECTO
INNER JOIN PRODUCTO PR 
ON PP . PRODUCTO = PR . PRODUCTO
WHERE P . PROYECTO = 1