SELECT
P . NOMBRE PROYECTO , PP . DESCRIPCION PRODUCTO, 
FM . NOMBRE NOMBRE_MENSAJE, FM . REMITENTE, FM . ASUNTO , 
T . NOMBRE TIPO_MENSAJE , TI . NOMBRE INFORMACION
FROM MENSAJE M
INNER JOIN PROYECTO P 
ON P . PROYECTO = M . PROYECTO
INNER JOIN PRODUCTO PP 
ON PP . PRODUCTO = M . PRODUCTO
INNER JOIN FORMATO_MENSAJE FM 
ON FM . COD_FORMATO = M . COD_FORMATO
INNER JOIN TIPO T 
ON FM . COD_TIPO = T . COD_TIPO 
INNER JOIN TIPO_INFORMACION TI 
ON FM . COD_TIPO_INFORMACION = TI .COD_TIPO_INFORMACION