SELECT  DISTINCT 
P . NOMBRE PROYECTO ,  
CASE WHEN V . VALIDA  = 'TODOS' THEN 
'TODOS' ELSE 
PP . DESCRIPCION  END PRODUCTO, 
FM . NOMBRE NOMBRE_MENSAJE, FM . REMITENTE, FM . ASUNTO , 
T . NOMBRE TIPO_MENSAJE , TI . NOMBRE INFORMACION
FROM MENSAJE M
INNER JOIN PROYECTO P 
ON P . PROYECTO = M . PROYECTO
INNER JOIN PRODUCTO PP 
ON PP . PRODUCTO = M . PRODUCTO
INNER JOIN FORMATO_MENSAJE FM 
ON FM . COD_FORMATO = M . COD_FORMATO
INNER JOIN TIPO T 
ON FM . COD_TIPO = T . COD_TIPO 
INNER JOIN TIPO_INFORMACION TI 
ON FM . COD_TIPO_INFORMACION = TI .COD_TIPO_INFORMACION
INNER JOIN (
SELECT DISTINCT   CASE WHEN COUNT ( M . PRODUCTO )  >= P . CONTEO THEN 
'TODOS' 
ELSE 
'NO' END VALIDA , 
M . COD_FORMATO , M . PROYECTO 
FROM MENSAJE M 
INNER JOIN (
SELECT COUNT (PRODUCTO) CONTEO , PROYECTO FROM PRODUCTO_PROYECTO
GROUP BY PROYECTO
) P
ON M . PROYECTO = P . PROYECTO
GROUP BY M . COD_FORMATO , M . PROYECTO , P . CONTEO
) V
ON M . COD_FORMATO = V . COD_FORMATO 
AND M . PROYECTO = V . PROYECTO